# WALKMAN 

XBotInterface:
  urdf_path: "configs/ADVR_shared/bigman/urdf/bigman.urdf"
  srdf_path: "configs/ADVR_shared/bigman/srdf/bigman.srdf"
  joint_map_path: "configs/ADVR_shared/bigman/joint_map/bigman_ecat_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "AdvrCommandMessage"
  jointstate_message_type: "AdvrJointStateMessage"
  ft_topic_names: [] #["/ft_foot_1", "/ft_foot_2", "/ft_foot_3", "/ft_foot_4"]
  imu_topic_names: [] #["/imu_1_data", "/imu_2_data"]

RobotInterfaceXBotRT:
  subclass_name: "RobotInterfaceXBotRT"
  path_to_shared_lib: "libRobotInterfaceXBotRT.so"
  subclass_factory_name: "robot_interface_xbot_rt"

XBotRTPlugins:
  #plugins: ["ExoskeletonCommunicationPlugin", "TwoPriorityRtIkPlugin"]
  #plugins: ["ExoskeletonCommunicationPlugin", "HomingExample"]
  #plugins: ["HomingExample", "IkRosSharedMemoryPublisher", "OpenSotIk"]
  plugins: ["HomingExample"]
  #io_plugins: ["IkRosIo"]
  #plugins: ["ExoskeletonCommunicationPlugin"]
  #plugins: ["PlayJointSpaceDemo"] #, "TwoPriorityRtIkPlugin"]

MasterCommunicationInterface:
  framework_name: "ROS"
  
AdvrCommandMessage:
  subclass_name: "CommandAdvr"
  path_to_shared_lib: "libAdvrCommandMessage.so"
  subclass_factory_name: "advrcommandmessage_control_message"
  joint_service_name: "/bigman/position_controller/get_joint_names"
  command_topic_name: "/xbotcore/bigman/command"

AdvrJointStateMessage:
  subclass_name: "AdvrJointState"
  path_to_shared_lib: "libAdvrJointStateMessage.so"
  subclass_factory_name: "advrjointstate_jointstate_message"
  joint_state_topic_name: "/xbotcore/bigman/joint_states"

RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"
